version: "3.1"

services:
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    image: "microservice-postgres:latest"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - microservice

volumes:
  postgres:
    name: microservice-postgres

networks:
  microservice:
