version: "3.1"

services:
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    image: "microservice-postgres:latest"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres/.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - microservice

  api-gateway:
    build:
      context: grpc-nest
      dockerfile: api-gateway/Dockerfile
    image: "microservice-api-gateway:latest"
    restart: always
    ports:
      - 3000:3000
    networks:
      - microservice

  auth-svc:
    build:
      context: grpc-nest
      dockerfile: auth-svc/Dockerfile
    image: "microservice-auth-svc:latest"
    restart: always
    ports:
      - 3001:3001
    networks:
      - microservice

  order-svc:
    build:
      context: grpc-nest
      dockerfile: order-svc/Dockerfile
    image: "microservice-order-svc:latest"
    restart: always
    ports:
      - 3002:3002
    networks:
      - microservice

  product-svc:
    build:
      context: grpc-nest
      dockerfile: product-svc/Dockerfile
    image: "microservice-product-svc:latest"
    restart: always
    ports:
      - 3003:3003
    networks:
      - microservice

volumes:
  postgres:
    name: microservice-postgres

networks:
  microservice:
